FROM ghcr.io/windmill-labs/windmill:main

RUN wget https://get.helm.sh/helm-v3.10.1-linux-amd64.tar.gz && \
    tar -zxvf helm-v3.10.1-linux-amd64.tar.gz  && \
    mv linux-amd64/helm /usr/local/bin/helm &&\
    chmod +x /usr/local/bin/helm

CMD ["./windmill"]
