<script lang="ts">
	import { page } from '$app/stores'
	import { copyToClipboard } from '$lib/utils'
	import Tooltip from '$lib/components/Tooltip.svelte'
	import { workspaceStore } from '$lib/stores'
	import bash from 'svelte-highlight/languages/bash'
	import { Badge, Tabs, Tab, TabContent, Button } from '$lib/components/common'
	import Skeleton from '$lib/components/common/skeleton/Skeleton.svelte'
	import github from 'svelte-highlight/styles/github'

	import {
		DEFAULT_WEBHOOK_TYPE,
		SCRIPT_VIEW_SHOW_EXAMPLE_CURL,
		SCRIPT_VIEW_SHOW_CREATE_TOKEN_BUTTON
	} from '$lib/consts'
	import { Clipboard } from 'lucide-svelte'
	import Toggle from '$lib/components/Toggle.svelte'
	import { capitalize } from 'lodash'
	import UserSettings from '../UserSettings.svelte'
	import { Highlight } from 'svelte-highlight'
	import { typescript } from 'svelte-highlight/languages'

	let userSettings: UserSettings
	let includeToken: boolean = false

	export let loading: boolean = false
	export let webhooks: {
		async: {
			hash?: string
			path: string
		}
		sync: {
			hash?: string
			path: string
			get_path?: string
		}
	}
	export let path: string
	export let args: any
	export let scopes: string[] = []
	export let isFlow: boolean = false

	function curlCommand(async: boolean) {
		return `curl -H 'Content-Type: application/json' -H "Authorization: Bearer $TOKEN" -X POST -d '${JSON.stringify(
			args
		)}' ${$page.url.protocol}//${$page.url.hostname}/api/w/${$workspaceStore}/jobs/run${
			async ? '' : '_wait_result'
		}/p/${path}`
	}
</script>

<svelte:head>
	{@html github}
</svelte:head>
<UserSettings bind:this={userSettings} {scopes} />

<div class="p-2 flex flex-col">
	{#if SCRIPT_VIEW_SHOW_CREATE_TOKEN_BUTTON}
		<div class="flex flex-row-reverse my-2">
			<Button size="xs" color="light" variant="border" on:click={userSettings.openDrawer}>
				Create a Webhook-specific Token
				<Tooltip light>
					The token will have a scope such that it can only be used to trigger this script. It is
					safe to share as it cannot be used to impersonate you.
				</Tooltip>
			</Button>
		</div>
	{/if}

	<Skeleton {loading} layout={[[8.5]]} />
	<!-- svelte-ignore a11y-click-events-have-key-events -->
	<Tabs selected={DEFAULT_WEBHOOK_TYPE}>
		<Tab value="async">
			Async
			<Tooltip
				light
				documentationLink="https://www.windmill.dev/docs/core_concepts/webhooks#asynchronous"
			>
				Jobs can be triggered in asynchronous mode, meaning that the webhook is triggered, and the
				returning value is the uuid of the job assigned to execute the underlying code.
			</Tooltip>
		</Tab>
		<Tab value="sync">
			Sync

			<Tooltip
				light
				documentationLink="https://www.windmill.dev/docs/core_concepts/webhooks#asynchronous"
			>
				The second type of autogenerated endpoint is the synchronous webhook. This webhook triggers
				the execution, automatically extracts the underlying code's return value and returns it as
				the response.
			</Tooltip>
		</Tab>
		{#if SCRIPT_VIEW_SHOW_EXAMPLE_CURL}
			<Tab value="curl">Curl</Tab>
		{/if}
		<Tab value="fetch">Fetch</Tab>
		<svelte:fragment slot="content">
			{#each Object.keys(webhooks) as key}
				<TabContent value={key}>
					<div class="flex flex-col gap-4">
						{#each Object.keys(webhooks[key]) as type}
							{@const url = webhooks[key][type]}
							{@const href = $page.url.protocol + '//' + url}

							<div class="flex flex-col">
								<div class="pr-4 py-2 whitespace-nowrap">
									{#if type == 'get_path'}
										<Badge color="green">GET</Badge>
										<Tooltip>
											This webhook unlike the others which are all POST takes in a GET request. The
											payload must be passed as the query arg `payload` and encoded in JSON first,
											then in an URL safe base64. e.g: `encodeURIComponent(btoa(JSON.stringify({'{a: 2}'})))`
										</Tooltip>
									{:else}
										<Badge color="yellow">POST</Badge>
										<Badge color="blue">
											{`by ${capitalize(type)}`}
										</Badge>
									{/if}
								</div>

								<div
									class="px-2 py-1 border flex items-center cursor-pointer bg-gray-100 text-gray-900 justify-between rounded-md"
									on:click={(e) => {
										e.preventDefault()
										copyToClipboard(href)
									}}
								>
									<div class="text-xs whitespace-nowrap overflow-ellipsis">
										{includeToken ? `${url}?token=your_token` : url}
									</div>
									<Clipboard size={14} />
								</div>
							</div>
						{/each}
					</div>

					<div class="pr-4 py-3">
						<Toggle bind:checked={includeToken} options={{ right: 'Include token' }} size="xs" />
					</div>
				</TabContent>
			{/each}
			<TabContent value="curl" class="flex flex-col flex-1 h-full">
				{@const command = curlCommand(true)}

				<div class="flex flex-col gap-2">
					<div class="flex flex-row gap-8 my-4">
						<Toggle options={{ right: 'Include token' }} size="xs" />
						<Toggle options={{ right: 'Async', left: 'Sync' }} size="xs" />
						{#if !isFlow}
							<Toggle options={{ right: 'Hash', left: 'Path' }} size="xs" />
						{/if}
					</div>

					<Highlight
						language={bash}
						code={command}
						class="p-2 whitespace-pre-wrap border rounded-md"
					/>

					<Highlight
						language={bash}
						class="p-2 whitespace-pre-wrap border rounded-md"
						code={'//returns an UUID. Fetch until completed == true\n\ncurl -H "Authorization: Bearer $TOKEN" {$page.url.protocol}//{$page.url.hostname}/api/w/{$workspaceStore}/jobs_u/completed/get_result_maybe/$UUID"} class="p-2 whitespace-pre-wrap'}
					/>
				</div>
			</TabContent>
			<TabContent value="fetch" class="flex flex-col flex-1 h-full">
				<Highlight
					language={typescript}
					class="p-2 whitespace-pre-wrap border rounded-md"
					code={'fetch()'}
				/>
			</TabContent>
		</svelte:fragment>
	</Tabs>
</div>
