<script lang="ts">
	import { page } from '$app/stores'
	import Tooltip from '$lib/components/Tooltip.svelte'
	import { workspaceStore } from '$lib/stores'
	import bash from 'svelte-highlight/languages/bash'
	import { Tabs, Tab, TabContent, Button } from '$lib/components/common'
	import ToggleButtonGroup from '$lib/components/common/toggleButton-v2/ToggleButtonGroup.svelte'
	import ToggleButton from '$lib/components/common/toggleButton-v2/ToggleButton.svelte'
	import {
		DEFAULT_WEBHOOK_TYPE,
		SCRIPT_VIEW_SHOW_EXAMPLE_CURL,
		SCRIPT_VIEW_SHOW_CREATE_TOKEN_BUTTON
	} from '$lib/consts'
	import { ArrowDownRight, ArrowUpRight } from 'lucide-svelte'
	import UserSettings from '../UserSettings.svelte'
	import { Highlight } from 'svelte-highlight'
	import { typescript } from 'svelte-highlight/languages'
	import ClipboardPanel from './ClipboardPanel.svelte'

	let userSettings: UserSettings

	export let webhooks: {
		async: {
			hash?: string
			path: string
		}
		sync: {
			hash?: string
			path: string
			get_path?: string
		}
	}
	export let args: any
	export let scopes: string[] = []
	export let isFlow: boolean = false

	let webhookType: 'async' | 'sync' = DEFAULT_WEBHOOK_TYPE
	let requestType: 'hash' | 'path' | 'get_path' = isFlow ? 'path' : 'hash'
	let tokenType: 'query' | 'headers' = 'headers'

	$: if (webhookType === 'async' && requestType === 'get_path') {
		// Request type is not supported for async webhooks
		requestType = 'hash'
	}

	$: url = webhooks[webhookType][requestType]

	let token = 'YOUR_TOKEN'
</script>

<UserSettings bind:this={userSettings} {scopes} />

<div class="p-2 flex flex-col w-full gap-4">
	{#if SCRIPT_VIEW_SHOW_CREATE_TOKEN_BUTTON}
		<div class="flex flex-row justify-between my-2 gap-2">
			<input bind:value={token} placeholder="YOUR_TOKEN" class="!text-xs" />
			<Button size="xs" color="light" variant="border" on:click={userSettings.openDrawer}>
				Create a Webhook-specific Token
				<Tooltip light>
					The token will have a scope such that it can only be used to trigger this script. It is
					safe to share as it cannot be used to impersonate you.
				</Tooltip>
			</Button>
		</div>
	{/if}

	<div class="flex flex-col gap-2">
		<div class="flex flex-row justify-between">
			<div class="text-xs font-semibold flex flex-row items-center">Request type</div>
			<ToggleButtonGroup class="h-[30px] w-auto" bind:selected={webhookType}>
				<ToggleButton
					label="Async"
					value="async"
					tooltip="Jobs can be triggered in asynchronous mode, meaning that the webhook is triggered, and the returning value is the uuid of the job assigned to execute the underlying code."
				/>
				<ToggleButton
					label="Sync"
					value="sync"
					tooltip="The second type of autogenerated endpoint is the synchronous webhook. This webhook triggers the execution, automatically extracts the underlying code's return value and returns it as the response."
				/>
			</ToggleButtonGroup>
		</div>
		{#if !isFlow}
			<div class="flex flex-row justify-between">
				<div class="text-xs font-semibold flex flex-row items-center">Call method</div>
				<ToggleButtonGroup class="h-[30px] w-auto" bind:selected={requestType}>
					<ToggleButton
						label="Post by hash"
						value="hash"
						icon={ArrowUpRight}
						selectedColor="#fb923c"
					/>
					<ToggleButton
						label="Post by path"
						value="path"
						icon={ArrowUpRight}
						selectedColor="#fb923c"
					/>
					<ToggleButton
						label="Get by path"
						value="get_path"
						icon={ArrowDownRight}
						disabled={webhookType !== 'sync'}
						selectedColor="#14b8a6"
					/>
				</ToggleButtonGroup>
			</div>
		{/if}
		<div class="flex flex-row justify-between">
			<div class="text-xs font-semibold flex flex-row items-center">Token configuration</div>
			<ToggleButtonGroup class="h-[30px] w-auto" bind:selected={tokenType}>
				<ToggleButton label="Token in Query" value="query" />
				<ToggleButton label="Token in Headers" value="headers" />
			</ToggleButtonGroup>
		</div>
	</div>

	<!-- svelte-ignore a11y-click-events-have-key-events -->
	<Tabs selected="rest">
		<Tab value="rest" size="xs">REST</Tab>
		{#if SCRIPT_VIEW_SHOW_EXAMPLE_CURL}
			<Tab value="curl" size="xs">Curl</Tab>
		{/if}
		<Tab value="fetch" size="xs">Fetch</Tab>

		<svelte:fragment slot="content">
			<TabContent value="rest" class="flex flex-col flex-1 h-full ">
				<div class="flex flex-col gap-2">
					<ClipboardPanel
						title="Url"
						content={tokenType === 'query' ? `${url}?token=${token}` : url}
					/>

					{#if requestType !== 'get_path'}
						<ClipboardPanel title="Body" content={JSON.stringify(args, null, 2)} />
					{/if}

					<ClipboardPanel
						title="Headers"
						content={JSON.stringify(
							tokenType === 'query'
								? {
										'Content-Type': 'application/json'
								  }
								: {
										'Content-Type': 'application/json',
										Authorization: `Bearer ${token}`
								  },
							null,
							2
						)}
					/>
				</div>
			</TabContent>
			<TabContent value="curl" class="flex flex-col flex-1 h-full">
				<div class="flex flex-col gap-2">
					<Highlight
						language={bash}
						code={`${requestType !== 'get_path' ? `BODY='${JSON.stringify(args)}'` : ''}
URL=${tokenType === 'query' ? `${url}?token=${token}` : url}\n
curl -H 'Content-Type: application/json' ${
							tokenType === 'headers' ? `-H 'Authorization: Bearer ${token}' ` : ''
						}-X ${requestType === 'get_path' ? 'GET' : 'POST'} ${
							requestType !== 'get_path' ? `-d "$BODY" ` : ''
						}$URL
`}
						class="p-2 whitespace-pre-wrap border rounded-md"
					/>

					<Highlight
						language={bash}
						class="p-2 whitespace-pre-wrap border rounded-md"
						code={`${
							webhookType === 'sync'
								? 'echo $RESPONSE'
								: `UUID=$(echo $RESPONSE | jq -r .uuid)
URL=${$page.url.protocol}//${$page.url.hostname}/api/w/${$workspaceStore}/jobs_u/completed/get_result_maybe/$UUID
while true; do
		RESULT=$(curl -H "Authorization: Bearer $TOKEN" $URL)
		COMPLETED=$(echo $RESULT | jq .completed)
		if [ "$COMPLETED" = "true" ]; then
				echo 'Job result: ' $RESULT
				break
		else
				sleep 1
		fi
done`
						}`}
					/>
				</div>
			</TabContent>
			<TabContent value="fetch" class="flex flex-col flex-1 h-full">
				<Highlight
					language={typescript}
					class="p-2 whitespace-pre-wrap border rounded-md"
					code={`${
						requestType !== 'get_path' ? 'const body = ' + JSON.stringify(args, null, 2) : ''
					}
fetch(${tokenType === 'query' ? `\`${url}?token=${token}\`` : `\`${url}\``}, {
	method: '${requestType === 'get_path' ? 'GET' : 'POST'}',
	headers: {
		'Content-Type': 'application/json',
		${tokenType === 'headers' ? `'Authorization': 'Bearer ${token}',` : ''}
	},
	${requestType !== 'get_path' ? `body: body` : ''}
}).then(
	response => response.json()
).then(data => {
	${
		webhookType === 'sync'
			? 'console.log(data)'
			: `let UUID = data.uuid;
    let checkCompletion = setInterval(() => {
		fetch(\`${$page.url.protocol}//${$page.url.hostname}/api/w/${$workspaceStore}/jobs_u/completed/get_result_maybe/\$\{UUID\}\`, {
			method: 'GET',
			headers: {
					'Authorization': 'Bearer ${token}'
			}
		}).then(response => response.json())
		.then(data => {
			if (data.completed) {
				console.log('Job result: ', data);
				clearInterval(checkCompletion);
			}
		});
	}, 1000);`
	}
});`}
				/>
			</TabContent>
		</svelte:fragment>
	</Tabs>
</div>
