services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5433:5432"

  temporal:
    image: temporalio/auto-setup:latest
    depends_on:
      - postgres
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres
    ports:
      - "7233:7233"

  worker:
    image: temporal-benchmark-worker
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    restart: on-failure
