-- Add up migration script here
CREATE TYPE TRIGGER_KIND AS ENUM ('webhook', 'http', 'websocket', 'kafka', 'email');
ALTER TABLE capture ADD COLUMN is_flow BOOLEAN NOT NULL DEFAULT TRUE, ADD COLUMN trigger_kind TRIGGER_KIND NOT NULL DEFAULT 'webhook', ADD COLUMN trigger_extra JSONB;
ALTER TABLE capture ALTER COLUMN is_flow DROP DEFAULT, ALTER COLUMN trigger_kind DROP DEFAULT;
ALTER TABLE capture DROP CONSTRAINT capture_pkey;
ALTER TABLE capture ADD COLUMN id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE capture_config (
    workspace_id VARCHAR(50) NOT NULL,
    path VARCHAR(255) NOT NULL,
    is_flow BOOLEAN NOT NULL,
    trigger_kind TRIGGER_KIND NOT NULL,
    trigger_config JSONB NULL,
    owner VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    server_id VARCHAR(50) NULL,
    last_client_ping TIMESTAMPTZ NULL,
    last_server_ping TIMESTAMPTZ NULL,
    error TEXT NULL,
    PRIMARY KEY (workspace_id, path, is_flow, trigger_kind),
    FOREIGN KEY (workspace_id) REFERENCES workspace(id) ON DELETE CASCADE
);

