-- Add up migration script here
ALTER TABLE usr ALTER COLUMN email TYPE VARCHAR(255);
ALTER TABLE password ALTER COLUMN email TYPE VARCHAR(255);
ALTER TABLE token ALTER COLUMN email TYPE VARCHAR(255);
ALTER TABLE workspace_invite ALTER COLUMN email TYPE VARCHAR(255);