CREATE TABLE job (
  id UUID PRIMARY KEY,
  raw_code TEXT,
  raw_lock TEXT,
  raw_flow jsonb NULL,
  tag VARCHAR(50),
  workspace_id VARCHAR(50)
);

CREATE OR REPLACE VIEW queue_view AS
SELECT
    queue.id,
    queue.workspace_id,
    queue.parent_job,
    queue.created_by,
    queue.created_at,
    queue.started_at,
    queue.scheduled_for,
    queue.running,
    queue.script_hash,
    queue.script_path,
    queue.args,
    concat(coalesce(queue.logs, ''), coalesce(job_logs.logs, '')) as logs,
    coalesce(queue.raw_code, job.raw_code) as raw_code,
    queue.canceled,
    queue.canceled_by,
    queue.canceled_reason,
    queue.last_ping,
    queue.job_kind,
    queue.env_id,
    queue.schedule_path,
    queue.permissioned_as,
    queue.flow_status,
    coalesce(queue.raw_flow, job.raw_flow) as raw_flow,
    queue.is_flow_step,
    queue.language,
    queue.suspend,
    queue.suspend_until,
    queue.same_worker,
    coalesce(queue.raw_lock, job.raw_lock) as raw_lock,
    queue.pre_run_error,
    queue.email,
    queue.visible_to_owner,
    queue.mem_peak,
    queue.root_job,
    queue.leaf_jobs,
    queue.tag,
    queue.concurrent_limit,
    queue.concurrency_time_window_s,
    queue.timeout,
    queue.flow_step_id,
    queue.cache_ttl,
    queue.priority,
    job_logs.log_offset
FROM queue
LEFT JOIN job ON queue.id = job.id AND queue.workspace_id = job.workspace_id
LEFT JOIN job_logs ON queue.id = job_logs.job_id;

CREATE OR REPLACE VIEW completed_job_view AS
SELECT
    completed_job.id,
    completed_job.workspace_id,
    completed_job.parent_job,
    completed_job.created_by,
    completed_job.created_at,
    completed_job.duration_ms,
    completed_job.success,
    completed_job.script_hash,
    completed_job.script_path,
    completed_job.args,
    completed_job.result,
    concat(coalesce(completed_job.logs, ''), coalesce(job_logs.logs, '')) as logs,
    completed_job.deleted,
    coalesce(completed_job.raw_code, job.raw_code) as raw_code,
    completed_job.canceled,
    completed_job.canceled_by,
    completed_job.canceled_reason,
    completed_job.job_kind,
    completed_job.env_id,
    completed_job.schedule_path,
    completed_job.permissioned_as,
    completed_job.flow_status,
    coalesce(completed_job.raw_flow, job.raw_flow) as raw_flow,
    completed_job.is_flow_step,
    completed_job.language,
    completed_job.started_at,
    completed_job.is_skipped,
    coalesce(completed_job.raw_lock, job.raw_lock) as raw_lock,
    completed_job.email,
    completed_job.visible_to_owner,
    completed_job.mem_peak,
    completed_job.tag,
    completed_job.priority,
    job_logs.log_offset
FROM completed_job
LEFT JOIN job ON completed_job.id = job.id AND completed_job.workspace_id = job.workspace_id
LEFT JOIN job_logs ON completed_job.id = job_logs.job_id;
