CREATE TYPE ASSET_USAGE_KIND AS ENUM ('script', 'flow');
CREATE TYPE ASSET_USAGE_ACCESS_TYPE AS ENUM ('r', 'w', 'rw');
CREATE TYPE ASSET_KIND AS ENUM ('s3object', 'resource');

CREATE TABLE asset (
  workspace_id VARCHAR(50) NOT NULL REFERENCES workspace(id) ON DELETE CASCADE ON UPDATE CASCADE,
  path VARCHAR(255) NOT NULL,
  kind ASSET_KIND NOT NULL,
  usage_access_type ASSET_USAGE_ACCESS_TYPE NOT NULL,
  usage_path VARCHAR(255) NOT NULL,
  usage_kind ASSET_USAGE_KIND NOT NULL
);