ALTER TABLE workspace_runnable_dependencies
DROP CONSTRAINT workspace_runnable_dependencies_path_exclusive;

ALTER TABLE workspace_runnable_dependencies
DROP CONSTRAINT fk_workspace_runnable_dependencies_app_path;

ALTER TABLE workspace_runnable_dependencies DROP COLUMN app_path;

ALTER TABLE workspace_runnable_dependencies ALTER flow_path SET NOT NULL;

ALTER TABLE workspace_runnable_dependencies
RENAME TO flow_workspace_runnables;
