ALTER TABLE asset
  ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN id BIGSERIAL UNIQUE;
DO
$do$
BEGIN
  ALTER TYPE ASSET_USAGE_KIND ADD VALUE 'job';
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Couldn''t create ASSET_USAGE_KIND::job: %', SQLERRM;
END
$do$;
