ALTER TABLE resource ADD COLUMN IF NOT EXISTS labels text[];
ALTER TABLE variable ADD COLUMN IF NOT EXISTS labels text[];

ALTER TABLE script ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE flow ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE app ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE raw_app ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE schedule ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE http_trigger ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE websocket_trigger ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE kafka_trigger ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE nats_trigger ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE mqtt_trigger ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE postgres_trigger ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE sqs_trigger ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE gcp_trigger ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;
ALTER TABLE email_trigger ALTER COLUMN labels DROP NOT NULL, ALTER COLUMN labels DROP DEFAULT;

UPDATE script SET labels = NULL WHERE labels = '{}';
UPDATE flow SET labels = NULL WHERE labels = '{}';
UPDATE app SET labels = NULL WHERE labels = '{}';
UPDATE raw_app SET labels = NULL WHERE labels = '{}';
UPDATE schedule SET labels = NULL WHERE labels = '{}';
