/**
 * Bundles the frontend's raw-app session recorder into a browser script the dev
 * server can serve, and writes it as a string constant the CLI bundle carries.
 *
 * The recorder is not re-implemented here: `wmill app dev --recording` must
 * produce the exact recording format the players read, and the event
 * classification it encodes is the hard part. The one adaptation is the `$state`
 * rune — outside Svelte the store's fields are read through its getters, so the
 * rune is stripped and the values become plain `let`s.
 *
 * Run `bun run gen:dev-recorder` after touching anything under
 * frontend/src/lib/components/recording/; test/dev_recorder_unit.test.ts fails
 * when the committed bundle no longer matches those sources.
 */
import * as esbuild from "esbuild";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const RECORDING_DIR = join(
  import.meta.dir,
  "..",
  "frontend",
  "src",
  "lib",
  "components",
  "recording",
);
/** The modules that end up in the bundle (`types.ts` is imported as types only,
 * so it is erased and cannot change the output). */
export const RECORDER_SOURCES = [
  "rawAppSnapshot.ts",
  "rawAppRecording.svelte.ts",
];
const OUT_FILE = join(
  import.meta.dir,
  "src",
  "commands",
  "app",
  "devRecorderBundle.gen.ts",
);

export function hashRecorderSources(dir: string = RECORDING_DIR): string {
  const hash = createHash("sha256");
  for (const file of RECORDER_SOURCES) {
    hash.update(file);
    hash.update(readFileSync(join(dir, file)));
  }
  return hash.digest("hex");
}

/** Reactivity has no meaning in a plain browser script, and the store exposes
 * every rune-backed field through a getter, so `$state(x)` collapses to `x`. */
function stripRunes(source: string, file: string): string {
  const runes = source.match(/\$state[\w.]*\s*\(?/g) ?? [];
  const unsupported = runes.filter((r) => r.replace(/\s/g, "") !== "$state(");
  if (unsupported.length > 0) {
    throw new Error(
      `${file} uses ${
        unsupported.join(", ")
      }, which this generator cannot strip. ` +
        `Keep the recorder store free of runes beyond \`$state(...)\`.`,
    );
  }
  return source.replace(/\$state\s*\(/g, "(");
}

const runeStripper: esbuild.Plugin = {
  name: "strip-svelte-runes",
  setup(build) {
    build.onLoad({ filter: /\.svelte\.ts$/ }, (args) => ({
      contents: stripRunes(readFileSync(args.path, "utf-8"), args.path),
      loader: "ts",
    }));
  },
};

if (import.meta.main) {
  const result = await esbuild.build({
    stdin: {
      contents: `export { createRawAppRecording } from './rawAppRecording.svelte'`,
      resolveDir: RECORDING_DIR,
      loader: "ts",
    },
    plugins: [runeStripper],
    bundle: true,
    format: "iife",
    globalName: "__wmillRecorder",
    target: "es2020",
    minify: true,
    write: false,
    legalComments: "none",
  });

  const js = result.outputFiles[0].text;
  writeFileSync(
    OUT_FILE,
    `// Generated by cli/generate-dev-recorder.ts — do not edit.\n` +
      `// Run \`bun run gen:dev-recorder\` from cli/ to rebuild it from\n` +
      `// frontend/src/lib/components/recording/.\n\n` +
      `/** SHA-256 of the frontend sources this bundle was built from. */\n` +
      `export const DEV_RECORDER_SOURCE_HASH = ${
        JSON.stringify(hashRecorderSources())
      };\n\n` +
      `/** IIFE exposing \`createRawAppRecording\` on \`window.__wmillRecorder\`. */\n` +
      `export const DEV_RECORDER_BUNDLE = ${JSON.stringify(js)};\n`,
    "utf-8",
  );
  console.log(
    `Wrote ${OUT_FILE} (${Math.round(js.length / 1024)} KB of bundled JS)`,
  );
}
