[package]
name = "windmill-parser-ts-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]
name = "windmill_parser_ts_wasm"
path = "./src/lib.rs"

[dev-dependencies]
windmill-parser.workspace = true
wasm-bindgen-test.workspace = true

[dependencies]
windmill-parser-ts.workspace = true
wasm-bindgen.workspace = true
serde_json.workspace = true