[package]
name = "windmill-tool-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
windmill-tool-registry = { path = "../windmill-tool-registry" }
http = "0.2"
serde_json = "1"
inventory = "0.3"
schemars = "0.8" 