export { default as LanguageIcon } from './LanguageIcon.svelte'
export { default as BashIcon } from './Bash.svelte'
export { default as GoIcon } from './Go.svelte'
export { default as PythonIcon } from './Python.svelte'
export { default as TypeScriptIcon } from './TypeScript.svelte'
