{
 "title": "Windmill Monitoring",
 "description": "Monitor Windmill workers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Workers running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(worker_started)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Busy workers",
   "type": "gauge",
   "description": "Percentage of workers currently executing a job",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_busy) / sum(worker_started)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Servers total active DB connection",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(pool_connections_active{job=\"windmill_server\"})) / sum(pool_connections_max{job=\"windmill_server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workers total active DB connection",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(pool_connections_active{job=\"windmill_worker\"})) / sum(pool_connections_max{job=\"windmill_worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database connections MAX and ACTIVE per worker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "pool_connections_max{job=\"windmill_worker\"}",
     "legendFormat": "max - {{instance}}"
    },
    {
     "expr": "pool_connections_max{job=\"windmill_worker\"} - pool_connections_idle{job=\"windmill_worker\"}",
     "legendFormat": "active - {{instance}}"
    }
   ]
  },
  {
   "title": "Database connections MAX and ACTIVE per server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "pool_connections_max{job=\"windmill_server\"}",
     "legendFormat": "max - {{instance}}"
    },
    {
     "expr": "pool_connections_max{job=\"windmill_server\"} - pool_connections_idle{job=\"windmill_server\"}",
     "legendFormat": "active - {{instance}}"
    }
   ]
  },
  {
   "title": "Pull duration 95th percentile per worker",
   "type": "timeseries",
   "description": "Duration of the pull-job operation on each worker when a job is returned (pull returning \"no job to run\" are excluded)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(worker_pull_duration_bucket{has_job=\"true\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Save completed job duration",
   "type": "timeseries",
   "description": "Duration to save a completed job for each worker",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(worker_save_duration_bucket[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Flow INITIAL transition duration 95th percentile per worker",
   "type": "timeseries",
   "description": "Duration of the flow initial transition before the first job is pushed to the queue for each worker",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(worker_flow_initial_transition_duration_bucket[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Flow transition duration 95th percentile per worker",
   "type": "timeseries",
   "description": "Duration of the flow transitions for each worker",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(worker_flow_transition_duration_bucket[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total number of jobs processed per time unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(tag) (rate(worker_execution_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}