/**
 * Windmill server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.6.1
 * Contact: contact@windmill.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FlowStatusModule } from './FlowStatusModule.ts';
import { HttpFile } from '../http/http.ts';

export class FlowStatus {
    'step': number;
    'modules': Array<FlowStatusModule>;
    'failureModule': FlowStatusModule;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "step",
            "baseName": "step",
            "type": "number",
            "format": ""
        },
        {
            "name": "modules",
            "baseName": "modules",
            "type": "Array<FlowStatusModule>",
            "format": ""
        },
        {
            "name": "failureModule",
            "baseName": "failure_module",
            "type": "FlowStatusModule",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FlowStatus.attributeTypeMap;
    }

    public constructor() {
    }
}

