<script lang="ts">
	import AppEditor from '$lib/components/apps/editor/AppEditor.svelte'
	import { AppService, type AppWithLastVersion } from '$lib/gen'
	import { workspaceStore } from '$lib/stores'
	import { replaceState } from '$app/navigation'
	import { goto } from '$lib/navigation'
	import { sendUserToast } from '$lib/toast'
	import DiffDrawer from '$lib/components/DiffDrawer.svelte'
	import type { App } from '$lib/components/apps/types'
	import DraftEditorModals from '$lib/components/common/confirmationModal/DraftEditorModals.svelte'
	import { UserDraftDbSyncer } from '$lib/userDraftDbSyncer.svelte'
	import { type OtherDraftUser } from '$lib/components/common/confirmationModal/OtherUsersDraftsModal.svelte'
	import { stateSnapshot } from '$lib/svelte5Utils.svelte'
	import { emptyApp } from '$lib/components/apps/editor/appUtils'
	import { importStore } from '$lib/components/apps/store'
	import { untrack } from 'svelte'
	import { page } from '$app/state'
	import { UserDraft } from '$lib/userDraft.svelte'

	let app = $state(undefined as (AppWithLastVersion & { value: any }) | undefined)
	let savedApp:
		| {
				value: App
				path: string
				summary: string
				policy: any
				custom_path?: string
		  }
		| undefined = $state(undefined)
	let redraw = $state(0)
	let path = page.params.path ?? ''
	/** True when no deployed app exists at the URL path — either we
	 * landed via `/apps/add → ?new_draft=true` (no fetch yet) or the
	 * fetch came back with `no_deployed`. Controls the editor's deploy
	 * flow: `createApp` vs `updateApp`. Survives `loadApp` reloads
	 * (e.g. workspace switch on the same draft path). Flips back to
	 * false once a deployed row exists at this path. */
	let isNewApp = $state(false)
	let otherDraftsUsers = $state<OtherDraftUser[]>([])
	let loadedFromDraft = $state(false)
	let othersModalOpen = $state(false)
	let draftSavedAt = $state<string | undefined>(undefined)
	let deployedAt = $state<string | undefined>(undefined)

	/** Increments per `loadApp` call. Stale loads (e.g. when picker
	 * navigation races a draft-discard reload) bail at the next checkpoint
	 * after their captured token no longer matches. */
	let loadAppToken = 0
	async function loadApp(opts: { getDraft?: boolean } = {}): Promise<void> {
		const getDraft = opts.getDraft ?? true
		const tok = ++loadAppToken
		// `?new_draft=true` (set by `/apps/add`'s redirect) means we landed
		// on a fresh `u/{user}/draft_{uuid}` path that's never been saved.
		// Skip the backend fetch (it would 404), seed an empty app with
		// `path = ''` so the `Path` widget's `initPath` calls `reset()`
		// and generates the friendly `<random_adj>_app` name. Anything
		// non-empty (even `u/{user}/`) is parsed verbatim and the
		// friendly seed never fires. Strip the flag last.
		if (page.url.searchParams.get('new_draft') === 'true') {
			// Suspend autosave for the new-draft bootstrap: the seed
			// `app` assignment + AppEditor's `firstMirror` mirror are
			// programmatic writes that shouldn't POST as the user's
			// first edit. AppEditor lifts the suspension in `onMount`
			// once mount-time effects have settled.
			UserDraft.stopSync('app', page.params.path ?? '')
			// No deployed row at the autogenerated `draft_{uuid}` URL
			// path — the editor's Deploy button must `createApp` at
			// the user-typed path, not `updateApp` at the URL.
			isNewApp = true
			const url = new URL(window.location.href)
			url.searchParams.delete('new_draft')
			window.history.replaceState(window.history.state, '', url.toString())
			// Backend's `Policy` requires `execution_mode` — an empty
			// object fails to deserialize on deploy. `publisher` is the
			// default authoring mode (the only other authored option is
			// `anonymous`, which the deploy header lets the user opt
			// into).
			const emptyPolicy = { execution_mode: 'publisher' } as any
			// One-shot import handoff: "Import from YAML/JSON" / "Build
			// app" from a script or flow writes $importStore and routes
			// to /apps/add, which redirects here. Wrapped exports carry
			// { summary, value, policy }; bare ones are the App value.
			const importRaw = $importStore
			if (importRaw) {
				$importStore = undefined
				sendUserToast('Loaded from YAML/JSON')
			}
			let seedSummary = ''
			let seedValue = emptyApp() as any
			let seedPolicy = emptyPolicy
			if (importRaw) {
				if ('value' in importRaw) {
					seedSummary = importRaw.summary ?? ''
					seedValue = importRaw.value
					seedPolicy = importRaw.policy ?? emptyPolicy
				} else {
					seedValue = importRaw
				}
			}
			app = {
				summary: seedSummary,
				value: seedValue,
				path: '',
				policy: seedPolicy,
				custom_path: undefined,
				versions: [] as any,
				id: 0 as any,
				extra_perms: {},
				created_at: new Date().toISOString(),
				created_by: '',
				raw_app: false
			} as unknown as AppWithLastVersion & { value: any }
			savedApp = {
				summary: seedSummary,
				value: seedValue,
				path: '',
				policy: seedPolicy
			}
			return
		}
		let backendApp = await AppService.getAppByPath({
			path: page.params.path ?? '',
			workspace: $workspaceStore!,
			getDraft
		})
		if (tok !== loadAppToken) return
		otherDraftsUsers = (backendApp.other_drafts_users ?? []) as OtherDraftUser[]
		if ($workspaceStore && path) {
			UserDraftDbSyncer.recordRemoteSync(
				{ workspace: $workspaceStore, itemKind: 'app', path },
				backendApp.draft_saved_at
			)
		}
		// Apply the user's saved draft to `.value`. The autosave for apps
		// writes the raw `App` (just the editor's working value) — when a
		// draft exists the backend sends it back in `.draft`, and the
		// rest of this loader (plus AppEditor's `app={app.value}` prop)
		// expects the `AppWithLastVersion` `{summary, value, path,
		// policy, ...}` shape. Two branches:
		//   - `no_deployed`: no deployed row exists. The response body is
		//     a best-effort stand-in (same JSON as `.draft`). Synthesize
		//     the wrapper with the saved App as `.value` and empty
		//     deployed-metadata defaults.
		//   - deployed + draft: keep the deployed metadata, replace
		//     `.value` with the saved App.
		const savedDraftApp = (backendApp as any).draft as App | undefined
		// Re-evaluate the "new app" signal on each load — flips to true
		// for draft-only paths and back to false once a deploy lands.
		isNewApp = !!backendApp.no_deployed
		if (backendApp.no_deployed) {
			backendApp = {
				summary: '',
				value: (savedDraftApp ?? {}) as App,
				path: page.params.path ?? '',
				// Backend's `Policy` requires `execution_mode` —
				// matches the new-app seed above.
				policy: { execution_mode: 'publisher' } as any,
				custom_path: undefined,
				versions: undefined as any,
				id: 0 as any,
				extra_perms: {},
				created_at: new Date().toISOString(),
				created_by: '',
				raw_app: false,
				is_draft: true,
				draft_saved_at: backendApp.draft_saved_at,
				no_deployed: true
			} as unknown as typeof backendApp
		} else if (savedDraftApp) {
			backendApp = { ...backendApp, value: savedDraftApp } as typeof backendApp
		}
		if (backendApp.is_draft) {
			loadedFromDraft = true
		}
		// App's deploy timestamp is `created_at` (sourced from the latest
		// `app_version.created_at`); compare with `draft_saved_at` so
		// DraftEditorModals can fire the StaleDraftModal. Skip when
		// `no_deployed` — there's no deployed baseline to be older than.
		draftSavedAt = backendApp.draft_saved_at as string | undefined
		deployedAt = backendApp.no_deployed ? undefined : (backendApp.created_at as string | undefined)
		const backendApp_ = structuredClone(stateSnapshot(backendApp))
		savedApp = {
			summary: backendApp_.summary,
			value: backendApp_.value as App,
			path: backendApp_.path,
			policy: backendApp_.policy,
			custom_path: backendApp_.custom_path
		}
		// Backend canonical: assign the fresh response onto `app`. The
		// path-change $effect upstream sets `app = undefined` before
		// calling loadApp, which unmounts AppEditor and releases the
		// UserDraft entry — so when `app = backendApp` triggers a
		// remount, the new handle starts fresh with no stale draft to
		// dedup against. (`UserDraft.discard` was here previously but
		// it POSTs `value: null` server-side, which surfaced as a
		// spurious autosave on every /edit visit.)
		app = backendApp
	}

	$effect(() => {
		// Re-run on workspace OR path change so navigating from one app editor
		// to another (e.g. via the workspace picker) reloads the new app.
		const currentPath = page.params.path
		if ($workspaceStore && currentPath !== undefined) {
			untrack(() => {
				// Clear the app so AppEditor unmounts; it will remount once loadApp
				// completes with fresh data, re-initializing its internal stores.
				app = undefined
				path = currentPath
				loadApp()
			})
		}
	})

	async function restoreDeployed() {
		if (!savedApp) {
			sendUserToast('Could not restore to deployed', true)
			return
		}
		diffDrawer?.closeDrawer()
		UserDraft.discard('app', path, undefined)
		goto(`/apps/edit/${savedApp.path}`)
		await loadApp()
		redraw++
	}

	let diffDrawer: DiffDrawer | undefined = $state()

	function onRestore(ev: any) {
		sendUserToast('App restored from previous deployment')
		app = ev.detail
		const app_ = structuredClone(stateSnapshot(app!))
		savedApp = {
			summary: app_.summary,
			value: app_.value as App,
			path: app_.path,
			policy: app_.policy,
			custom_path: app_.custom_path
		}
		redraw++
	}
</script>

<DiffDrawer bind:this={diffDrawer} {restoreDeployed} />
<DraftEditorModals
	workspace={$workspaceStore ?? ''}
	itemKind="app"
	{path}
	{otherDraftsUsers}
	editPathFor={(forkedPath) => `/apps/edit/${forkedPath}`}
	onLoadFromServer={async () => {
		// AppEditor's `stateApp` is captured once at mount and doesn't
		// react to prop changes, so a plain loadApp() reload would update
		// `app` but leave the editor displaying the conflicting local
		// state. `redraw++` remounts AppEditor against the fresh `app`.
		await loadApp()
		redraw++
	}}
	getLocalDraft={() => app?.value}
	bind:othersModalOpen
	{draftSavedAt}
	{deployedAt}
	onLoadLatestDeploy={async () => {
		UserDraft.remove('app', path)
		await loadApp({ getDraft: false })
		redraw++
	}}
/>

{#key redraw}
	{#if app}
		<div class="h-screen">
			<AppEditor
				onSavedNewAppPath={(url) => {
					goto(`/apps/edit/${url}`)
					if (app) {
						app.path = url
					}
				}}
				on:restore={onRestore}
				summary={app.summary}
				app={app.value}
				newPath={app.value?.draft_path ?? app.path}
				path={page.params.path ?? ''}
				policy={app.policy}
				bind:savedApp
				{diffDrawer}
				version={app.versions ? app.versions[app.versions.length - 1] : undefined}
				newApp={isNewApp}
				replaceStateFn={(path) => replaceState(path, page.state)}
				gotoFn={(path, opt) => goto(path, opt)}
				onResetToDeployed={async () => {
					UserDraft.remove('app', path)
					await loadApp({ getDraft: false })
					redraw++
				}}
				{loadedFromDraft}
				othersDraftsCount={otherDraftsUsers.length}
				onOpenOthersDrafts={() => (othersModalOpen = true)}
			/>
		</div>
	{/if}
{/key}
