/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddGranularAclsRequest {
    #[serde(rename = "owner")]
    pub owner: String,
    #[serde(rename = "write", skip_serializing_if = "Option::is_none")]
    pub write: Option<bool>,
}

impl AddGranularAclsRequest {
    pub fn new(owner: String) -> AddGranularAclsRequest {
        AddGranularAclsRequest {
            owner,
            write: None,
        }
    }
}


