/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuditLog {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "operation")]
    pub operation: Operation,
    #[serde(rename = "action_kind")]
    pub action_kind: ActionKind,
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

impl AuditLog {
    pub fn new(id: i32, timestamp: String, username: String, operation: Operation, action_kind: ActionKind) -> AuditLog {
        AuditLog {
            id,
            timestamp,
            username,
            operation,
            action_kind,
            resource: None,
            parameters: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operation {
    #[serde(rename = "jobs.run")]
    JobsPeriodRun,
    #[serde(rename = "scripts.create")]
    ScriptsPeriodCreate,
    #[serde(rename = "scripts.update")]
    ScriptsPeriodUpdate,
    #[serde(rename = "users.create")]
    UsersPeriodCreate,
    #[serde(rename = "users.delete")]
    UsersPeriodDelete,
    #[serde(rename = "users.setpassword")]
    UsersPeriodSetpassword,
    #[serde(rename = "users.update")]
    UsersPeriodUpdate,
    #[serde(rename = "users.login")]
    UsersPeriodLogin,
    #[serde(rename = "users.token.create")]
    UsersPeriodTokenPeriodCreate,
    #[serde(rename = "users.token.delete")]
    UsersPeriodTokenPeriodDelete,
    #[serde(rename = "variables.create")]
    VariablesPeriodCreate,
    #[serde(rename = "variables.delete")]
    VariablesPeriodDelete,
    #[serde(rename = "variables.update")]
    VariablesPeriodUpdate,
}

impl Default for Operation {
    fn default() -> Operation {
        Self::JobsPeriodRun
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ActionKind {
    #[serde(rename = "Created")]
    Created,
    #[serde(rename = "Updated")]
    Updated,
    #[serde(rename = "Delete")]
    Delete,
    #[serde(rename = "Execute")]
    Execute,
}

impl Default for ActionKind {
    fn default() -> ActionKind {
        Self::Created
    }
}

