/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BranchOneBranchesInner {
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(rename = "expr")]
    pub expr: String,
    #[serde(rename = "modules")]
    pub modules: Vec<crate::models::FlowModule>,
}

impl BranchOneBranchesInner {
    pub fn new(expr: String, modules: Vec<crate::models::FlowModule>) -> BranchOneBranchesInner {
        BranchOneBranchesInner {
            summary: None,
            expr,
            modules,
        }
    }
}


