/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateVariable {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "is_secret")]
    pub is_secret: bool,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<i32>,
    #[serde(rename = "is_oauth", skip_serializing_if = "Option::is_none")]
    pub is_oauth: Option<bool>,
}

impl CreateVariable {
    pub fn new(path: String, value: String, is_secret: bool, description: String) -> CreateVariable {
        CreateVariable {
            path,
            value,
            is_secret,
            description,
            account: None,
            is_oauth: None,
        }
    }
}


