/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAccountRequest {
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
    #[serde(rename = "expires_in")]
    pub expires_in: i32,
    #[serde(rename = "owner")]
    pub owner: String,
    #[serde(rename = "client")]
    pub client: String,
}

impl CreateAccountRequest {
    pub fn new(refresh_token: String, expires_in: i32, owner: String, client: String) -> CreateAccountRequest {
        CreateAccountRequest {
            refresh_token,
            expires_in,
            owner,
            client,
        }
    }
}


