/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateWorkspace {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "domain")]
    pub domain: String,
}

impl CreateWorkspace {
    pub fn new(id: String, name: String, username: String, domain: String) -> CreateWorkspace {
        CreateWorkspace {
            id,
            name,
            username,
            domain,
        }
    }
}


