/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FlowModuleStopAfterIf {
    #[serde(rename = "skip_if_stopped", skip_serializing_if = "Option::is_none")]
    pub skip_if_stopped: Option<bool>,
    #[serde(rename = "expr")]
    pub expr: String,
}

impl FlowModuleStopAfterIf {
    pub fn new(expr: String) -> FlowModuleStopAfterIf {
        FlowModuleStopAfterIf {
            skip_if_stopped: None,
            expr,
        }
    }
}


