/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FlowStatusModuleBranchall {
    #[serde(rename = "branch")]
    pub branch: i32,
    #[serde(rename = "len")]
    pub len: i32,
}

impl FlowStatusModuleBranchall {
    pub fn new(branch: i32, len: i32) -> FlowStatusModuleBranchall {
        FlowStatusModuleBranchall {
            branch,
            len,
        }
    }
}


