/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FlowStatusModuleIterator {
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<i32>,
    #[serde(rename = "itered", skip_serializing_if = "Option::is_none")]
    pub itered: Option<Vec<serde_json::Value>>,
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<serde_json::Value>,
}

impl FlowStatusModuleIterator {
    pub fn new() -> FlowStatusModuleIterator {
        FlowStatusModuleIterator {
            index: None,
            itered: None,
            args: None,
        }
    }
}


