/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSettings200Response {
    #[serde(rename = "workspace_id", skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<String>,
    #[serde(rename = "slack_name", skip_serializing_if = "Option::is_none")]
    pub slack_name: Option<String>,
    #[serde(rename = "slack_team_id", skip_serializing_if = "Option::is_none")]
    pub slack_team_id: Option<String>,
    #[serde(rename = "slack_command_script", skip_serializing_if = "Option::is_none")]
    pub slack_command_script: Option<String>,
}

impl GetSettings200Response {
    pub fn new() -> GetSettings200Response {
        GetSettings200Response {
            workspace_id: None,
            slack_name: None,
            slack_team_id: None,
            slack_command_script: None,
        }
    }
}


