/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "r#type")]
pub enum InputTransform {
    #[serde(rename = "javascript")]
    JavascriptTransform {
        #[serde(rename = "expr")]
        expr: String,
    },
    #[serde(rename = "static")]
    StaticTransform {
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
}

impl Default for InputTransform {
    fn default() -> Self {
        InputTransform::StaticTransform { value: None }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "javascript")]
    Javascript,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Javascript
    }
}
