/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InviteUserRequest {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "is_admin")]
    pub is_admin: bool,
}

impl InviteUserRequest {
    pub fn new(email: String, is_admin: bool) -> InviteUserRequest {
        InviteUserRequest {
            email,
            is_admin,
        }
    }
}


