/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JavascriptTransform {
    #[serde(rename = "expr")]
    pub expr: String,
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl JavascriptTransform {
    pub fn new(expr: String, r#type: RHashType) -> JavascriptTransform {
        JavascriptTransform {
            expr,
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "javascript")]
    Javascript,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Javascript
    }
}

