/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListOAuthConnects200ResponseValue {
    #[serde(rename = "extra_params", skip_serializing_if = "Option::is_none")]
    pub extra_params: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
}

impl ListOAuthConnects200ResponseValue {
    pub fn new() -> ListOAuthConnects200ResponseValue {
        ListOAuthConnects200ResponseValue {
            extra_params: None,
            scopes: None,
        }
    }
}


