/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListHubFlows200Response {
    #[serde(rename = "flows", skip_serializing_if = "Option::is_none")]
    pub flows: Option<Vec<crate::models::ListHubFlows200ResponseFlowsInner>>,
}

impl ListHubFlows200Response {
    pub fn new() -> ListHubFlows200Response {
        ListHubFlows200Response {
            flows: None,
        }
    }
}


