/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MainArgSignatureArgsInner {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "typ")]
    pub typ: Box<crate::models::MainArgSignatureArgsInnerTyp>,
    #[serde(rename = "has_default", skip_serializing_if = "Option::is_none")]
    pub has_default: Option<bool>,
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<serde_json::Value>,
}

impl MainArgSignatureArgsInner {
    pub fn new(name: String, typ: crate::models::MainArgSignatureArgsInnerTyp) -> MainArgSignatureArgsInner {
        MainArgSignatureArgsInner {
            name,
            typ: Box::new(typ),
            has_default: None,
            default: None,
        }
    }
}


