/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MainArgSignatureArgsInnerTypOneOf2ObjectInnerTypOneOf {
    #[serde(rename = "str")]
    pub str: Option<serde_json::Value>,
}

impl MainArgSignatureArgsInnerTypOneOf2ObjectInnerTypOneOf {
    pub fn new(str: Option<serde_json::Value>) -> MainArgSignatureArgsInnerTypOneOf2ObjectInnerTypOneOf {
        MainArgSignatureArgsInnerTypOneOf2ObjectInnerTypOneOf {
            str,
        }
    }
}


