/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MainArgSignatureArgsInnerTyp {
    #[serde(rename = "resource")]
    pub resource: Option<String>,
    #[serde(rename = "str")]
    pub str: Option<Vec<String>>,
    #[serde(rename = "object")]
    pub object: Vec<crate::models::MainArgSignatureArgsInnerTypOneOf2ObjectInner>,
    #[serde(rename = "list")]
    pub list: Option<Box<crate::models::MainArgSignatureArgsInnerTypOneOf3List>>,
}

impl MainArgSignatureArgsInnerTyp {
    pub fn new(resource: Option<String>, str: Option<Vec<String>>, object: Vec<crate::models::MainArgSignatureArgsInnerTypOneOf2ObjectInner>, list: Option<crate::models::MainArgSignatureArgsInnerTypOneOf3List>) -> MainArgSignatureArgsInnerTyp {
        MainArgSignatureArgsInnerTyp {
            resource,
            str,
            object,
            list: if let Some(x) = list {Some(Box::new(x))} else {None},
        }
    }
}


