/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MainArgSignatureArgsInnerTypOneOf3 {
    #[serde(rename = "list")]
    pub list: Option<Box<crate::models::MainArgSignatureArgsInnerTypOneOf3List>>,
}

impl MainArgSignatureArgsInnerTypOneOf3 {
    pub fn new(list: Option<crate::models::MainArgSignatureArgsInnerTypOneOf3List>) -> MainArgSignatureArgsInnerTypOneOf3 {
        MainArgSignatureArgsInnerTypOneOf3 {
            list: if let Some(x) = list {Some(Box::new(x))} else {None},
        }
    }
}


