/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OpenFlowWPath {
    #[serde(rename = "summary")]
    pub summary: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::FlowValue>,
    #[serde(rename = "schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<serde_json::Value>,
    #[serde(rename = "path")]
    pub path: String,
}

impl OpenFlowWPath {
    pub fn new(summary: String, value: crate::models::FlowValue, path: String) -> OpenFlowWPath {
        OpenFlowWPath {
            summary,
            description: None,
            value: Box::new(value),
            schema: None,
            path,
        }
    }
}


