/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Retry {
    #[serde(rename = "constant", skip_serializing_if = "Option::is_none")]
    pub constant: Option<Box<crate::models::RetryConstant>>,
    #[serde(rename = "exponential", skip_serializing_if = "Option::is_none")]
    pub exponential: Option<Box<crate::models::RetryExponential>>,
}

impl Retry {
    pub fn new() -> Retry {
        Retry {
            constant: None,
            exponential: None,
        }
    }
}


