/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Script {
    #[serde(rename = "workspace_id", skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<String>,
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "path")]
    pub path: String,
    /// The first element is the direct parent of the script, the second is the parent of the first, etc 
    #[serde(rename = "parent_hashes", skip_serializing_if = "Option::is_none")]
    pub parent_hashes: Option<Vec<String>>,
    #[serde(rename = "summary")]
    pub summary: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "created_by")]
    pub created_by: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<serde_json::Value>,
    #[serde(rename = "deleted")]
    pub deleted: bool,
    #[serde(rename = "is_template")]
    pub is_template: bool,
    #[serde(rename = "extra_perms")]
    pub extra_perms: ::std::collections::HashMap<String, bool>,
    #[serde(rename = "lock", skip_serializing_if = "Option::is_none")]
    pub lock: Option<String>,
    #[serde(rename = "lock_error_logs", skip_serializing_if = "Option::is_none")]
    pub lock_error_logs: Option<String>,
    #[serde(rename = "language")]
    pub language: Language,
    #[serde(rename = "kind")]
    pub kind: Kind,
}

impl Script {
    pub fn new(hash: String, path: String, summary: String, content: String, created_by: String, created_at: String, archived: bool, deleted: bool, is_template: bool, extra_perms: ::std::collections::HashMap<String, bool>, language: Language, kind: Kind) -> Script {
        Script {
            workspace_id: None,
            hash,
            path,
            parent_hashes: None,
            summary,
            description: None,
            content,
            created_by,
            created_at,
            archived,
            schema: None,
            deleted,
            is_template,
            extra_perms,
            lock: None,
            lock_error_logs: None,
            language,
            kind,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Language {
    #[serde(rename = "python3")]
    Python3,
    #[serde(rename = "deno")]
    Deno,
    #[serde(rename = "go")]
    Go,
}

impl Default for Language {
    fn default() -> Language {
        Self::Python3
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "script")]
    Script,
    #[serde(rename = "failure")]
    Failure,
    #[serde(rename = "trigger")]
    Trigger,
    #[serde(rename = "command")]
    Command,
    #[serde(rename = "approval")]
    Approval,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Script
    }
}

