/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TruncatedToken {
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "expiration", skip_serializing_if = "Option::is_none")]
    pub expiration: Option<String>,
    #[serde(rename = "token_prefix")]
    pub token_prefix: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "last_used_at")]
    pub last_used_at: String,
}

impl TruncatedToken {
    pub fn new(token_prefix: String, created_at: String, last_used_at: String) -> TruncatedToken {
        TruncatedToken {
            label: None,
            expiration: None,
            token_prefix,
            created_at,
            last_used_at,
        }
    }
}


