/*
 * Windmill server API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.39.0
 * Contact: contact@windmill.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Usage {
    #[serde(rename = "duration_ms", skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i32>,
    #[serde(rename = "jobs", skip_serializing_if = "Option::is_none")]
    pub jobs: Option<i32>,
    #[serde(rename = "flows", skip_serializing_if = "Option::is_none")]
    pub flows: Option<i32>,
}

impl Usage {
    pub fn new() -> Usage {
        Usage {
            duration_ms: None,
            jobs: None,
            flows: None,
        }
    }
}


