import { redirect } from '@sveltejs/kit'
import { base } from '$app/paths'
import { getUsernameForNamespace } from '$lib/userNamespace'
import { randomUUID } from '$lib/components/flows/conversations/FlowChatManager.svelte'

/**
 * Shared `load` for every `/{scripts,flows,apps,apps_raw}/add` route.
 *
 * Each route used to mount its `+page.svelte` and `goto` from `onMount` —
 * painting one blank frame before navigating, hence the white flash.
 * Doing the work in `load` lets SvelteKit cancel the route transition
 * and head straight for the edit page with no DOM round-trip.
 *
 * Mints a fresh `u/<username>/draft_<uuid>` path and issues a 307 to
 * `{base}/{editPrefix}/<that-path>?new_draft=true&<existing-params>`.
 * The `new_draft=true` flag tells the edit route to seed an empty
 * editor instead of 404-ing on the autogenerated path.
 *
 * Uses the project's `randomUUID` helper rather than
 * `crypto.randomUUID()` — the WebCrypto version is unavailable on
 * non-secure origins (HTTP, local IPs over LAN), and self-hosted
 * Windmill instances frequently run that way.
 */
export function makeDraftAddLoad(editPrefix: string) {
	return ({ url }: { url: URL }) => {
		const username = getUsernameForNamespace()
		const uuid = randomUUID()
		const params = new URLSearchParams(url.searchParams)
		params.set('new_draft', 'true')
		redirect(307, `${base}/${editPrefix}/u/${username}/draft_${uuid}?${params.toString()}`)
	}
}
