name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: windmill
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: changeme
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: "Generate backend client"
        working-directory: ./frontend
        run: |
          npm install
          npm run generate-backend-client
          npm run build

      - name: "Rust server"
        working-directory: ./backend
        env:
          DATABASE_URL: postgres://admin:changeme@localhost:5432/windmill
          BASE_INTERNAL_URL: http://localhost/
        run: cargo run
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./frontend
          wait-on: http://localhost:8000

