name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: windmill
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: changeme
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: "Create backend env file"
        run: |
          cd ./backend
          touch .env
          echo DATABASE_URL=postgres://admin:changeme@localhost/windmill >> .env
          echo BASE_INTERNAL_URL=http://localhost/ >> .env
          cat .env

      - name: "Generate backend client"
        working-directory: ./frontend
        run: |
          npm install
          npm run generate-backend-client

      - name: Install Caddy
        run: |
          sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
          sudo apt update
          sudo apt install caddy
          caddy stop

      - name: "Caddy"
        working-directory: ./frontend
        run: caddy run --config ./Caddyfile

      - name: "Rust server"
        working-directory: ./backend
        run: cargo run
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./frontend
          start: npm run dev
          wait-on: http://localhost

