name: Publish powershell-client
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish_gallery:
    runs-on: ubicloud-standard-8
    steps:
      - uses: actions/checkout@v4
      - run: . ./powershell-client/publish.ps1
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
